name       : tuba
version    : 0.4.0
release    : 1
source     :
    - https://github.com/GeopJr/Tuba/archive/refs/tags/v0.4.0.tar.gz : f3ab01b2b987f1eca4056beed17db3924e1e8f9cfd3938cccbce63b7ab1a44a3
license    : GPL-3.0-or-later
component  : network.clients
summary    : Browse the Fediverse, a gtk mastodon application.
description: |
    Browse the Fediverse, a gtk mastodon application.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk4)
    - pkgconfig(gtksourceview-5)
    - pkgconfig(libadwaita-1)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-3.0)
    - vala
    - webp-pixbuf-loader
setup      : |
    %meson_configure \
        -Ddistro=true
build      : |
    %ninja_build
install    : |
    %ninja_install
